### PR TITLE
fix(iot-thinggroups): support deleting dynamic thing groups

### PR DESCRIPTION
**Pull request by ekristen**
Attempts to fix deleting dynamic thing groups which was brought up https://github.com/rebuy-de/aws-nuke/issues/1199.

Creating dynamic thing groups are bit more complicated so this is tough to test.

### CODE REVIEW

**Comment by ekristen** [comment]
@rstalbow can you test one of the builds from the zip file located here? https://github.com/ekristen/aws-nuke/actions/runs/8291642110/artifacts/1328506343

This is my rewrite of aws-nuke that I've been working on. [docs and reason for why the rewrite is here](https://ekristen.github.io/aws-nuke) If you modify your configuration to target just `IoTThingGroup` then you can specifically test this without affecting anything else. 

If you'd like to help test this version out, I would appreciate it, but if not, I understand.

**Comment by rstalbow** [comment]
Great! Sorry I didnt get a chance to test the build

**Comment by ekristen** [comment]
Feel free to test now and let me know if you run into issues

**Pull request merged**
