### PR TITLE
fix(bedrockagent): set Bedrock Datasource data deletion policy to RETAIN before deleting it

### LINKED ISSUE #431: Bedrock Agent Datasource: DELETE_UNSUCCESSFUL when data is already deleted
When aws-nuke delete the S3 bucket associated with the Berock datasource before deleting the datasource itself, the datasource cannot be removed. The error message message displayed is:

```
Unable to delete data from vector store for data source with ID ABCDEF. Check your vector store configurations and permissions and retry your request. If the issue persists, consider updating the dataDeletionPolicy of the data source to RETAIN and retry your request.
```

This error can be fixed by updating the datasource before deletion, and setting the data retention policy to RETAIN. This way, AWS will not try to delete the corresponding ghost data, and can delete the datasource properly.

Fixing this bug will have a consequence: deleting a Bedrock datasource, and filtering the S3 buckets from aws-nuke config will retain the data from corresponding S3 bucket datasource.

### PR DESCRIPTION
**Pull request by npellegrin**
Closes #431

### CODE REVIEW

**Comment by npellegrin** [comment]
Output with the implemented fix.
The failed datasource previously on DELETE_UNSUCCESSFUL status can be properly deleted.

```
us-east-1 - BedrockKnowledgeBase - 5OZDA2VLM7 - [ID: "5OZDA2VLM7", Name: "knowledge-base-quick-start-idsv5", Status: "DELETE_UNSUCCESSFUL"] - would remove
us-east-1 - BedrockDataSource - QMTF2MTCVF - [ID: "QMTF2MTCVF", KnowledgeBaseID: "5OZDA2VLM7", Name: "knowledge-base-quick-start-40k4o-data-source", Status: "DELETE_UNSUCCESSFUL"] - would remove
Scan complete: 2 total, 2 nukeable, 0 filtered.

Do you really want to nuke the account with the ID 571875759811 and the alias 'icelab-account60'?
Do you want to continue? Enter account alias to continue.
> icelab-account60

us-east-1 - BedrockKnowledgeBase - 5OZDA2VLM7 - [ID: "5OZDA2VLM7", Name: "knowledge-base-quick-start-idsv5", Status: "DELETE_UNSUCCESSFUL"] - triggered remove
us-east-1 - BedrockDataSource - QMTF2MTCVF - [ID: "QMTF2MTCVF", KnowledgeBaseID: "5OZDA2VLM7", Name: "knowledge-base-quick-start-40k4o-data-source", Status: "DELETE_UNSUCCESSFUL"] - triggered remove

Removal requested: 2 waiting, 0 failed, 0 skipped, 0 finished

us-east-1 - BedrockKnowledgeBase - 5OZDA2VLM7 - [ID: "5OZDA2VLM7", Name: "knowledge-base-quick-start-idsv5", Status: "DELETE_UNSUCCESSFUL"] - waiting
us-east-1 - BedrockDataSource - QMTF2MTCVF - [ID: "QMTF2MTCVF", KnowledgeBaseID: "5OZDA2VLM7", Name: "knowledge-base-quick-start-40k4o-data-source", Status: "DELETE_UNSUCCESSFUL"] - waiting

Removal requested: 2 waiting, 0 failed, 0 skipped, 0 finished

us-east-1 - BedrockKnowledgeBase - 5OZDA2VLM7 - [ID: "5OZDA2VLM7", Name: "knowledge-base-quick-start-idsv5", Status: "DELETE_UNSUCCESSFUL"] - removed
us-east-1 - BedrockDataSource - QMTF2MTCVF - [ID: "QMTF2MTCVF", KnowledgeBaseID: "5OZDA2VLM7", Name: "knowledge-base-quick-start-40k4o-data-source", Status: "DELETE_UNSUCCESSFUL"] - removed

Removal requested: 0 waiting, 0 failed, 0 skipped, 2 finished

Nuke complete: 0 failed, 0 skipped, 2 finished.
```

**Comment by npellegrin** [comment]
CI linter fixed, ready for review ❤️

**Review by ekristen — APPROVED** [review]

**Comment by ekristen** [comment]
And just like that, it's released :) thanks

**Pull request merged**
