### PR TITLE
feat: remove EC2 instances tags before termination

### PR DESCRIPTION
**Pull request by Petersoj**
PR for #138 with proper naming conventions and commit signing.

### CODE REVIEW

**Comment by ekristen** [comment]
hey @Petersoj thanks for the PR. I will review it here shortly. Sounds like I also need to write some docs up on opening a PR and how you can edit previous commits to format to semantic messages and sign, etc.

**Comment by Petersoj** [comment]
Well there is already some documentation in the contributing guidelines [here](https://github.com/ekristen/aws-nuke/blob/main/CONTRIBUTING.md#commits) about signing and commit message conventions, but I overlooked that guide on my first two PRs haha.

**Comment by ekristen** [comment]
Confirmed working. I will write a test for it in a follow up PR later. I'm working on adding mock and integration tests so that **real** tests for some of the more important and complex resources can run in AWS.

**Comment by Petersoj** [comment]
Awesome! Thanks for the fast release!

**Comment by ekristen** [comment]
That's part of my fork design, release faster with automation, not left to a human to cut a release.

**Pull request merged**
