### PR TITLE
feat(bedrock): add bedrock custom models, customization jobs, provisioned throughput and logging configuration

### LINKED ISSUE #160: [resource] Bedrock
It could be useful to add some Bedrock resources.

SDK go reference: https://docs.aws.amazon.com/sdk-for-go/api/service/bedrock/

### PR DESCRIPTION
**Pull request by npellegrin**
Closes #160

### CODE REVIEW

**Comment by npellegrin** [comment]
I have not tested this part on read infrastructure for now. Will try to write some unit tests 😃 

The current GO SDK version prevent implementing Bedrock Guardrails and Bedrock Evaluation Jobs, I will put it in another PR to have this one green.

**Comment by ekristen** [comment]
Mocks would be a good place to start. I do have examples of integration tests that require full AWS credentials to run. 

Look for `_mock_test.go` for mock related on how to create the mocks for the service. Writing mocks requiring some additional alterations to the source. Ideally since this is net new we want to run against real resources too or at least get real outputs back from the API to create the mocks to ensure we have proper coverage.

**Comment by ekristen** [comment]
@npellegrin are you going to have time to finish this up or should we close it for the time being?

**Comment by npellegrin** [comment]
Refactored a bit and implemented standards from project. Still need some work to test all resources types, because provisioned throughput can be expensive if I do not delete it immediately after creation.

Tested deleting logging configuration for now:

```
us-east-1 - BedrockModelInvocationLoggingConfiguration - default - [] - triggered remove

Removal requested: 1 waiting, 0 failed, 1 skipped, 0 finished

us-east-1 - BedrockModelInvocationLoggingConfiguration - default - [] - waiting

Removal requested: 1 waiting, 0 failed, 1 skipped, 0 finished

us-east-1 - BedrockModelInvocationLoggingConfiguration - default - [] - removed

Removal requested: 0 waiting, 0 failed, 1 skipped, 1 finished

Nuke complete: 0 failed, 1 skipped, 1 finished.
```

**Pull request merged**
