### PR TITLE
feat(cloudwatchlogs-loggroup): honor api rate limits

### LINKED ISSUE #239: CloudWatchLogsLogGroup Rate Limit Exceeded
This account has 13317 log groups. And yes, the "ThrottlingException: Rate exceeded" consistently happen during "Listing CloudWatchLogsLogGroup" even if I target log groups exclusively.

_Originally posted by @YuriGal in https://github.com/ekristen/aws-nuke/issues/237#issuecomment-2258284443_

### PR DESCRIPTION
**Pull request by ekristen**
This implements rate limiting on querying the api for CloudWatch Logs based on defaults available here https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html

Resolves #239

### CODE REVIEW

**Comment by ekristen** [comment]
Binaries available here https://github.com/ekristen/aws-nuke/actions/runs/10406287208

@YuriGal want to test it out?

**Comment by YuriGal** [comment]
Cool! Will do, thanks!

**Comment by YuriGal** [comment]
Would it be possible to publish it as a pre-release? The way our service is setup it downloads the nuke from the releases.

**Pull request merged**
