### PR TITLE
feat: migrate aws nuke

### PR DESCRIPTION
**Pull request by chenz4027**
https://issues.redhat.com/browse/OCM-12734

### CODE REVIEW

**Comment by ekristen** [comment]
I am not sure what your intention is here and I cannot view the issue but this is walk backwards on this tool. I will not be accepting this PR as it stands. If you'd like to open an issue and explain the problem in more detail or get me access to the redhat issue.

**Comment by chenz4027** [comment]
@ekristen Hey Erik, sorry I didn't realize that you don't have permission to the redhat issue. Let me summarize the purpose of this PR.

Essentially the description for that issue is:
```
*WHAT*

The current aws-nuke project is not maintained and the project is archived. We need to migrate to the new maintained project to ensure we can keep up to date with CVE's

*HOW*
Migrate to current supported project - https://github.com/ekristen/aws-nuke

*DONE*
- Cluster Cleaner uses https://github.com/ekristen/aws-nuke
- ```

Cluster cleaner is an internal repository that we use to clean up aws resources like clusters, roles, etc. I'm not sure if you can view it but I'll just paste the link here: https://gitlab.cee.redhat.com/service/uhc-clusters-cleaner

In cluster cleaner, we would need to use the cmd, awsutil and config, hence this PR.

Regarding the next step, would you prefer me to open an issue under this repository and we start some discussions on what's the best approach?

**Comment by ekristen** [comment]
It's not clear to me why you want to open a PR. This is the new active aws-nuke, you simply need to source your binaries from this project and see the 1 breaking change which is that you need to pass `run` in.  The entire structure of the project was gutted and changed and the bulk of the code was moved to a library.

I've got no access to the issue or the uhc-clusters-cleaner either, that seems to be private as well. 

If you are using golang, you will need to port your project over to use the new code here, not the other way around.

**Comment by chenz4027** [comment]
Agreed @ekristen , I think I can start with replacing the old aws-nuke with the new project & new nuke. Frankly speaking I should do that first to be honest. Will keep you posted on how that goes.

**Comment by chenz4027** [comment]
Thanks so much @ekristen 👍 Yeah I will definitely shoot an email if I ran into any issues. Appreciate your efforts for all the work you did in the aws-nuke project, it's truely amazing!

**Comment by ekristen** [comment]
You are welcome. Thank you for your kind words. It's greatly appreciated.

**Pull request closed without merging**
