### PR TITLE
fix(elasticache): use ID instead of name for default user filter

### PR DESCRIPTION
**Pull request by Petersoj**
There can be multiple ElastiCache users with `name` of "default", but only one with `ID` of "default", which cannot be deleted.

### CODE REVIEW

**Comment by Petersoj** [comment]
Not sure why `golangci-lint` check is still failing.

**Comment by ekristen** [comment]
weird @Petersoj for some reason in CI it detects a value that should be a const, but I can't duplicate it with the same config locally with the same version. Let me see if I can figure this out.

**Comment by ekristen** [comment]
@Petersoj can you rebase on the latest main, I added provisions so it won't error. I can't figure out why it's throwing an error for your branch but not mine, must be something due to it being a fork that I can't replicate, but if you rebase it should clear right now.

**Comment by Petersoj** [comment]
Looks like GitHub's "Update Branch" functionality does a merge instead of a rebase. My bad. Can open a new PR if you'd like.

**Pull request merged**
