### PR TITLE
feat(bedrock): add guardrails and evaluation jobs

### PR DESCRIPTION
**Pull request by npellegrin**
Similar to #161 but requires upgrading AWS SDK version.

### CODE REVIEW

**Comment by ekristen** [comment]
@npellegrin are you going to have time to finish this up or should we close it for the time being?

**Comment by npellegrin** [comment]
Sorry I did not realized this PR and #161 are pending. I have some time this week to look at it again, I will do some changes on it, test on a real account and flip the PR to "ready" once done 😃

**Comment by ekristen** [comment]
Awesome thank you so much.

**Comment by npellegrin** [comment]
New resources:

- BedrockGuardrail
- BedrockEvaluationJob

Both support tags. Filtering is enabled for model evaluation already in "stopped" state.

Scan with feature activated:

```
us-east-1 - BedrockGuardrail - txq90g37kft9 - [ID: "txq90g37kft9", Name: "test", Status: "READY", Version: "DRAFT", tag:testtag1: "testvalue", tag:zzz: "zafafx"] - would remove
us-east-1 - BedrockEvaluationJob - test - [Arn: "arn:aws:bedrock:us-east-1:000000000000:evaluation-job/0mkxhxrmjqzi", Name: "test", Status: "Stopped", tag:testzz: "testaa"] - already stopped
Scan complete: 2 total, 1 nukeable, 1 filtered.
````

Delete with feature activated for guardrail:

````
us-east-1 - BedrockGuardrail - txq90g37kft9 - [ID: "txq90g37kft9", Name: "test", Status: "READY", Version: "DRAFT", tag:testtag1: "testvalue", tag:zzz: "zafafx"] - removed

Removal requested: 0 waiting, 0 failed, 1 skipped, 1 finished

Nuke complete: 0 failed, 1 skipped, 1 finished.
````

Delete with feature activated for model evaluation:

```
us-east-1 - BedrockEvaluationJob - test - [Arn: "arn:aws:bedrock:us-east-1:000000000000:evaluation-job/0mkxhxrmjqzi", Name: "test", Status: "InProgress"] - triggered remove

Removal requested: 1 waiting, 0 failed, 0 skipped, 0 finished

us-east-1 - BedrockEvaluationJob - test - [Arn: "arn:aws:bedrock:us-east-1:000000000000:evaluation-job/0mkxhxrmjqzi", Name: "test", Status: "InProgress"] - waiting

Removal requested: 1 waiting, 0 failed, 0 skipped, 0 finished

us-east-1 - BedrockEvaluationJob - test - [Arn: "arn:aws:bedrock:us-east-1:000000000000:evaluation-job/0mkxhxrmjqzi", Name: "test", Status: "InProgress"] - removed
```

**Comment by npellegrin** [comment]
Ready for review on this one @ekristen 😃

**Pull request merged**
