### PR TITLE
feat: structured logging

### LINKED ISSUE #154: [idea] structured logs/report
Rather than rely on string parsing such as this tool [oijkn/aws-nuke-exporter](https://github.com/oijkn/aws-nuke-exporter), `aws-nuke` could have an option to output structured logs (`--output` or `--json` flag).

### PR DESCRIPTION
**Pull request by ekristen**
## Overview

This implements structured logging.  

## Example

```console
> aws-nuke - 3.0.0-dev - dirty
Do you really want to nuke the account with the ID 637423565883 and the alias 'no-alias-637423565883'?
Waiting 3s before continuing.
{"level":"info","msg":"filtered: cannot delete AWS managed key","owner":"us-east-1","prop:ID":"4960b196-e3e1-4f46-b82e-764ae098bada","prop:Manager":"AWS","prop:State":"Enabled","prop:_tagPrefix":"tag","resource":"4960b196-e3e1-4f46-b82e-764ae098bada","state":7,"time":"2024-10-05T23:45:00-06:00","type":"KMSKey"}
{"level":"info","msg":"filtered: cannot delete AWS managed key","owner":"us-east-1","prop:ID":"49faf6ef-ae89-4203-bb29-1bc32be20228","prop:Manager":"AWS","prop:State":"Enabled","prop:_tagPrefix":"tag","resource":"49faf6ef-ae89-4203-bb29-1bc32be20228","state":7,"time":"2024-10-05T23:45:00-06:00","type":"KMSKey"}
{"level":"info","msg":"filtered: cannot delete AWS managed key","owner":"us-east-1","prop:ID":"bfec52f0-a84c-4c78-a305-368918386251","prop:Manager":"AWS","prop:State":"Enabled","prop:_tagPrefix":"tag","resource":"bfec52f0-a84c-4c78-a305-368918386251","state":7,"time":"2024-10-05T23:45:00-06:00","type":"KMSKey"}
Scan complete: 3 total, 0 nukeable, 3 filtered.

No resource to delete.
```

### Running It

**Note:** this omits standard required options like configs.

```console
aws-nuke --log-format=json
```

there is a shortcut `--json` CLI option as well which means `--log-format=json`

## Questions

1. Should everything be handled by the logging (i.e. version and wait for 3 seconds, etc)
2. Should properties be prefixed by `prop:` or should it be stripped

## Builds

You can clone and run the following command:

```console
goreleaser build --snapshot --clean --single-target
```

Resolves #154

### CODE REVIEW

**Comment by kieran-lowe** [comment]
Thanks a bunch for working on this! 👊

**Comment by ekristen** [comment]
@kieran-lowe my pleasure. feedback would be appreciated.

**Comment by cland** [comment]
Thanks for working on this @ekristen . 

Question on the logging format: 
How would it look after nuke has run and some resources have been removed, others failed or filtered etc? Will there be a 'Status' with possible values 'removed' | 'filtered' | 'failed' etc that one can then filter on when they process the json output? A useful outcome is a logfile that will enable users of the logfile to put together a summary almost like your https://ekristen.github.io/aws-nuke/cli-usage/#aws-nuke-explain-config summary but more reporting on that the nuke module has managed to do.

To tweak your example a bit, I am picturing something like this:

```
{"level":"info",nuke-status:"removed","msg":"remove successfully","owner":"us-east-1","prop:ID":"4960b196-e3e1-4f46-b82e-764ae098bada","prop:Manager":"AWS","prop:State":"Enabled","prop:_tagPrefix":"tag","resource":"4960b196-e3e1-4f46-b82e-764ae098bada","state":7,"time":"2024-10-05T23:45:00-06:00","type":"KMSKey"}
{"level":"info",nuke-status:"filtered","msg":"filtered: cannot delete AWS managed key","owner":"us-east-1","prop:ID":"49faf6ef-ae89-4203-bb29-1bc32be20228","prop:Manager":"AWS","prop:State":"Enabled","prop:_tagPrefix":"tag","resource":"49faf6ef-ae89-4203-bb29-1bc32be20228","state":7,"time":"2024-10-05T23:45:00-06:00","type":"KMSKey"}
{"level":"info",nuke-status:"failed","msg":"Failed: Cannot delete the directory because it still has authorized applications","owner":"us-east-1","prop:ID":"bfec52f0-a84c-4c78-a305-368918386251","prop:Manager":"AWS","prop:State":"Enabled","prop:_tagPrefix":"tag","resource":"bfec52f0-a84c-4c78-a305-368918386251","state":7,"time":"2024-10-05T23:45:00-06:00","type":"DirectoryServiceDirectory"}
{"level":"info","nuke-summary":{"total":3,"filtered":1,"removed":1,"failed":1}}

```



Apologies if this is already the case and I have missed it somehow but that's just my thoughts.

**Comment by ekristen** [comment]
Getting close to being mergeable -- new build available once this action finishes up https://github.com/ekristen/aws-nuke/actions/runs/12476251043

`state` - string of the state of the resource
`state_code` - internal integer of the state (might be removed)
`prop:PROPERT_NAME` - all properties on a resource are prefixed with `prop:`
`name` - this is the **STRING** representation or in the future the **primary/default** property (once I put that in place)

```json
{"level":"info","msg":"filtered: unable to delete, fargate managed","name":"arn:aws:ecs:us-east-2:637423565883:capacity-provider/FARGATE_SPOT","owner":"us-east-2","prop:ARN":"arn:aws:ecs:us-east-2:637423565883:capacity-provider/FARGATE_SPOT","prop:Name":"FARGATE_SPOT","prop:Status":"ACTIVE","state":"filtered","state_code":7,"time":"2024-12-23T19:55:16-07:00","type":"ECSCapacityProvider"}
{"level":"info","msg":"filtered: cannot delete group 'default'","name":"sg-0ad5cc8941267ed4f","owner":"us-east-2","prop:Name":"default","prop:OwnerID":"637423565883","state":"filtered","state_code":7,"time":"2024-12-23T19:55:16-07:00","type":"EC2SecurityGroup"}
{"component":"libnuke","filtered":408,"level":"info","msg":"Scan complete: 408 total, 0 nukeable, 408 filtered.\n","nukeable":0,"time":"2024-12-23T19:55:16-07:00","total":408}
{"component":"libnuke","level":"info","msg":"No resource to delete.","time":"2024-12-23T19:55:16-07:00"}
```

**Comment by ekristen** [comment]
@kieran-lowe @cland new builds, please test.

**Pull request merged**
